---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccount: {{ .Values.name }}
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.name }}
          env:
            - name: SECRET_NAME
              value: {{ .Values.secret.name | quote }}
            - name: SECRET_TYPE
              value: {{ .Values.secret.type | quote }}
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: INTERVAL
              value: {{ .Values.refresh_interval | quote }}
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 20m
              memory: 32Mi
