# Application name
name: ecr-secret-creator

# The namespace you want to deploy this service
namespace: default

# Use your own image for production
image: ghcr.io/dispatchitinc/ecr-k8s-secret-creator:0.1.1

env:
  SECRET_NAME: ecr-docker-secret
  SECRET_TYPE: kubernetes.io/dockerconfigjson
  AWS_REGION: us-east-2
  INTERVAL: 1200
