# Application name
name: ecr-secret-creator

# The namespace you want to deploy this service
namespace: default

# Use your own image for production
image: ghcr.io/dispatchitinc/ecr-k8s-secret-creator:0.2.12

secret:
  # This is the name of the secret applications
  # will reference to access the token
  name: ecr-docker-secret

  # No real need to change this from the default unless you
  # know what you're doing.
  type: kubernetes.io/dockerconfigjson

aws:
  # Region the API calls to get the ECR token
  region: us-east-2

# Seconds to refresh the secrets (this must be less than 12 hours as
# required by ECR session expiration). Defaults to 20 minutes.
refresh_interval: 1200

# A list of namespaces to insert this secret
target_namespaces: [default]

# List the registries that need to be validated (if you're using a different
# account for hosting your ECR repositories for example).
# Defaults to the current account/region.
target_registries: []

# In case you need to provide any library specific AWS environment
# credentials
env: {}
