name: "Daily/Trigger: Delete Old Caches"

on:
  schedule:
    - cron: "0 5 * * *" # 5am UTC daily (11pm/12am CT)
  workflow_dispatch:

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@881eb5957687193fa612bf74c0042adc78ea5e54
