name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.19
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Version & Changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      # - uses: imjasonh/setup-ko@v0.6
      # - name: Build & Push Image
      #   run: ko publish --tags ${{ steps.cz.outputs.version }} --bare ./cmd/ecr-k8s-secret-creator
      # - name: Update Image Version Tag
      #   uses: mingjun97/file-regex-replace@v1
      #   with:
      #     regex: 'ecr-k8s-secret-creator:([0-9\.]*)'
      #     replacement: ecr-k8s-secret-creator:${{ steps.cz.outputs.version }}
      #     include: deploy/values.yaml
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: Updated image tag version to ${{ steps.cz.outputs.version }}
