name: "Auto: Publish"

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        run: |
          go test -v ./...

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    needs: test
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Version & Changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true

  publish_container:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - run: git pull
      - uses: imjasonh/setup-ko@v0.8
      - name: Build & Push Image
        run: ko publish --tags ${{ needs.bump_version.outputs.version }} --bare ./cmd/ecr-k8s-secret-creator
      - name: Update Image Version Tag
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: 'ecr-k8s-secret-creator:([0-9\.]+)'
          replacement: ecr-k8s-secret-creator:${{ needs.bump_version.outputs.version }}
          include: charts/ecr-k8s-secret-creator/values.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Updated image tag version to ${{ needs.bump_version.outputs.version }}

  publish_helm_chart:
    needs: [ bump_version, publish_container ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git pull
      - name: Update Helm Chart Versions
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: ': ([0-9\.]+)'
          replacement: ': ${{ needs.bump_version.outputs.version }}'
          include: charts/ecr-k8s-secret-creator/Chart.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Updated image tag version to ${{ needs.bump_version.outputs.version }}
      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
