name: "Auto: Build & Test"

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        run: go test -v ./...

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          staticcheck ./...

      # - uses: dominikh/staticcheck-action@v1.3.0
      #   with:
      #     cache-key: ${{ github.event.pull_request.number || github.head_ref }}
      #     install-go: false
      #     version: "2022.1.3"

      - name: Build
        run: go build -v ./...
