name: "Auto: Build & Test"

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          go install honnef.co/go/tools/cmd/staticcheck
          go mod tidy
          staticcheck ./...
